# .github/workflows/build-push-lambda-image.yaml
name: Build and Push Lambda Docker Image to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'lambda-code/**'

env:
  AWS_REGION: ${{ secrets.AWS_REGION || 'ap-south-1' }}
  ECR_REPOSITORY: s3-file-logger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # *** CHANGE HERE: Use github.sha as the tag ***
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./lambda-code/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # *** ADD THIS STEP: Output the full image URI ***
      - name: Set Image URI Output
        id: set_image_uri
        run: |
          echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT
    outputs:
      image_uri: ${{ steps.set_image_uri.outputs.IMAGE_URI }}